# Generated by Django 4.1.7 on 2023-05-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('year_born', models.IntegerField()),
                ('year_died', models.IntegerField(null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='artists')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='paintings/'),
        ),
        migrations.AddField(
            model_name='painting',
            name='is_on_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='painting',
            name='museum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='app.museum'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='app.artist'),
        ),
    ]
