# Generated by Django 4.1.7 on 2023-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artist_museum_painting_image_painting_is_on_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
