# Generated by Django 4.1.7 on 2023-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_painting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='paintings/default.jpg', upload_to='paintings/'),
        ),
    ]
