name: Test suite
on: [push, pull_request]

jobs:
  run_test_suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run our Django unit tests
        run: |
          cd testproject
          pip3 install --user django
          python3 manage.py test
